### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber" : "1000000002",
  "amount" : 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber" : "1000000002",
  "amount" : 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "8cea28d1ca664da9b2297139de4a11e1",
  "accountNumber" : "1000000002",
  "amount" : 20000
}

### query transaction
GET http://localhost:8080/transaction/1f1b4140788544dfbea454e711eab10b